### ISSUE TITLE
Debugging from VS 2022

### ISSUE THREAD

**Issue by jfjoubert** [wegylexy/XPLM#1]
Hi, do you perhaps have any tips on setting up debugging in Visual Studio 2022?
When I attach to the xplane.exe process I keep on getting "The breakpoint will not currently be hit. No symbols have been loaded for this document." If I detach and reattach then I can get some breakpoints to be hit, but not on all lines of code. Just wondering if there's something I'm missing here.

**Comment by wegylexy** [comment]
Your code is AOT-compiled to native code like C/C++ and optimized, so it may not map every single line.
See https://github.com/dotnet/runtimelab/blob/feature/NativeAOT/docs/using-nativeaot/README.md for debugging and optimization.

**Comment by jfjoubert** [comment]
Thank you for the info. That explains it.
Thank you as well for this useful project.
