### ISSUE TITLE
Building for Mac and Linux

### ISSUE THREAD

**Issue by jfjoubert** [wegylexy/XPLM#2]
Hi.
What are the requirements for building a plugin for Mac and Linux? I'm currently only running a Windows PC and building a win-x64 plugin.

**Comment by wegylexy** [comment]
Linux (e.g. WSL, WSLg) x64 is required to target Linux; MacOS x64 is required to target MacOS. If the OS is not x64, see https://github.com/dotnet/runtimelab/blob/feature/NativeAOT/docs/using-nativeaot/compiling.md#cross-architecture-compilation

**Comment by jfjoubert** [comment]
Thanks.
