### ISSUE TITLE
Reading & Writing to Datarefs

### ISSUE THREAD

**Issue by jfjoubert** [wegylexy/XPLM#3]
Hi, could you perhaps provide some sample code to show the proper way of reading & writing values to the following Datarefs?
Int
Float
Double
FloatArray
IntArray
Data

For Int, Float and Double I'm using the AsInt, AsFloat and AsDouble "getter" and "setter" methods, but I'm not too sure about the FloatArray, IntArray and Data drefs.

Thanks,
Jean

**Comment by wegylexy** [comment]
Writing floats is already included here https://github.com/wegylexy/XPLM/blob/main/XPL/Program.cs#L37-L43 and reading is similar, i.e. `.Read(values)`, to copy into your buffer.
For data, you need to define your own unmanaged structure / blittable type.
