### ISSUE TITLE
Build broken with .NET 6.0.100-rc.1

### ISSUE THREAD

**Issue by jgennari** [wegylexy/XPLM#4]
It looks like .NET 6.0 RC1 introduces a breaking change with `using` directives. More info [here](https://docs.microsoft.com/en-us/dotnet/core/compatibility/sdk/6.0/implicit-namespaces-rc1). This is currently breaking the build with lots CS0246 compiler errors: 

`C:\Users\joey\source\Repos\XPLM\XPLM\Menu.cs(11,28): error CS0246: The type or namespace name 'IDisposable' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\jmg11\source\Repos\XPLM\refs\XPLM\XPLM.csproj]`

**Comment by wegylexy** [comment]
Probably disabled by default due to potential conflicts in legacy codes. RC1 broke some of my other projects too when I [Ctrl+R, Ctrl+G] during preview 7.
